name: build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    strategy:
      matrix:
        compiler: [gcc, clang]

    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'coretto'
        java-version: '21'

    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install static analysis tools
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck clang clang-tools
      
    - name: Static analysis
      run: |
        cppcheck --enable=all --error-exitcode=1 src/ || true

    - name: Setup compiler
      run: |
        if [ "${{ matrix.compiler }}" = "clang" ]; then
          echo "CC=clang" >> $GITHUB_ENV
        else
          echo "CC=gcc" >> $GITHUB_ENV
        fi
        
    - name: Compile nob
      run: |
        if [ ! -f nob ]; then
          $CC -Wall -Wextra -Werror nob.c -o nob
        fi
      
    - name: Build cooper project
      run: ./nob
      
    - name: Run tests with sanitizers
      # env:
      #   ASAN_OPTIONS: detect_leaks=1:abort_on_error=1
      #   UBSAN_OPTIONS: halt_on_error=1
      run: ./build/test_cooper